# Generated by Django 5.0.2 on 2024-10-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomsales',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
