# Generated by Django 5.0.2 on 2024-10-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100)),
                ('restaurant_address', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=100)),
                ('variation', models.CharField(blank=True, max_length=100, null=True)),
                ('item_quantity', models.FloatField()),
                ('item_price', models.FloatField()),
                ('item_total', models.FloatField()),
                ('converted_qty', models.FloatField(blank=True, null=True)),
                ('conversion_qty', models.FloatField(blank=True, null=True)),
                ('sub_total', models.FloatField()),
                ('grand_total', models.FloatField()),
                ('final_total', models.FloatField()),
                ('service_charge_amount', models.FloatField(blank=True, null=True)),
                ('service_charge_rate', models.FloatField(blank=True, null=True)),
                ('delivery_charges', models.FloatField(blank=True, null=True)),
                ('vat_amount', models.FloatField(blank=True, null=True)),
                ('cgst_amount', models.FloatField(blank=True, null=True)),
                ('sgst_amount', models.FloatField(blank=True, null=True)),
                ('igst', models.FloatField(blank=True, null=True)),
                ('total_consumption', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('outlet_discount', models.FloatField(blank=True, null=True)),
                ('aggregator_discount', models.FloatField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.CharField(max_length=255)),
            ],
        ),
    ]
