# Generated by Django 5.0.7 on 2024-10-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestraurantTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(max_length=100)),
                ('pos_invoice_no', models.CharField(max_length=100)),
                ('kot_no', models.CharField(max_length=100)),
                ('kot_id_k', models.CharField(max_length=100)),
                ('order_acceptance_time', models.DateTimeField(blank=True, null=True)),
                ('rider_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('received_time', models.DateTimeField(blank=True, null=True)),
                ('accepted_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('prepared_time_k', models.DateTimeField(blank=True, null=True)),
                ('punch_time_k', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('first_print_date', models.DateField(blank=True, null=True)),
                ('first_print_date_bsr', models.DateField(blank=True, null=True)),
                ('last_settlement_date', models.DateField(blank=True, null=True)),
                ('last_settlement_date_bsr', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
                ('kot_item_status', models.CharField(max_length=50)),
                ('order_type', models.CharField(max_length=50)),
                ('order_type_k', models.CharField(max_length=50)),
                ('delivery_status', models.CharField(max_length=50)),
                ('item_status_k', models.CharField(max_length=50)),
                ('settled_by', models.CharField(blank=True, max_length=50, null=True)),
                ('settled_by_bsr', models.CharField(blank=True, max_length=50, null=True)),
                ('settled_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('server_name', models.CharField(max_length=100)),
                ('biller_name', models.CharField(max_length=100)),
                ('biller', models.CharField(max_length=100)),
                ('brand_grouping', models.CharField(max_length=100)),
                ('client_sharing_code', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_type_detail', models.CharField(max_length=50)),
                ('order_from', models.CharField(max_length=100)),
                ('aggregator_order_no', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('non_taxable', models.BooleanField(default=False)),
                ('change_log', models.TextField(blank=True, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_paid_by_merchant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_paid_by_ecommerce', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('waived_off', models.BooleanField(default=False)),
                ('duration_in_minutes', models.IntegerField(blank=True, null=True)),
                ('duration_in_minutes_bsr', models.IntegerField(blank=True, null=True)),
                ('delivery_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
