# Generated by Django 5.0.7 on 2024-10-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_restrauranttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinforcementData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
