export const SIGNUP_PROJECT_REQUEST= "SIGNUP_PROJECT_REQUEST" 
export const SIGNUP_PROJECT_SUCCESS= "SIGNUP_PROJECT_SUCCESS" 
export const SIGNUP_PROJECT_FAIL= "SIGNUP_PROJECT_FAIL"

export const LOGIN_PROJECT_REQUEST= "LOGIN_PROJECT_REQUEST" 
export const LOGIN_PROJECT_SUCCESS= "LOGIN_PROJECT_SUCCESS" 
export const LOGIN_PROJECT_FAIL= "LOGIN_PROJECT_FAIL"

export const LOGOUT_PROJECT= "LOGOUT_PROJECT"